name: Run Playwright API Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-report
          path: playwright-report
